GET  http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiNDBrcGx1cyIsImlhdCI6MTU5NTYxNjk5OCwiZXhwIjoxNTk1NjE3MTE4LCJhdWQiOiJzZGRzZHMiLCJpc3MiOiI0MGtwbHVzIn0.yuZe-5oA7FiDmfl_uXSbKrXqJVzfV69SQvoPbmmk4Rg
###
GET  http://localhost:3000/WrongRoute

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"vigy.game@gmail.com",
    "password":"1234"
}


###Refresh token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU2MjIyNTcsImV4cCI6MTU5NTcwODY1NywiYXVkIjoic2Rkc2RzIiwiaXNzIjoiNDBrcGx1cyJ9.8oQYEXKqW0NmXNpwrm3Fi49lyAgtsCJW7sVA-kbyG-4"
}
